# Generated by Django 3.2.1 on 2024-06-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='table',
            new_name='category',
        ),
    ]
