# Generated by Django 3.2.1 on 2024-06-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_rename_table_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
