# Generated by Django 3.2.1 on 2024-06-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_profile_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
