# Generated by Django 3.2.1 on 2024-06-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='lms_app.status'),
            preserve_default=False,
        ),
    ]
