# Generated by Django 3.2.1 on 2024-06-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0010_auto_20240617_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_page',
            field=models.ImageField(blank=True, upload_to='cover/'),
        ),
    ]
