# Generated by Django 3.2.1 on 2024-06-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0013_book_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='book_count',
            field=models.IntegerField(default=0),
        ),
    ]
