# Generated by Django 3.2.1 on 2024-06-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0014_profile_book_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='book',
            new_name='books',
        ),
    ]
