# Generated by Django 3.2.1 on 2024-06-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0015_rename_book_cart_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.IntegerField(default=10),
        ),
    ]
