# Generated by Django 3.2.1 on 2024-06-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0017_alter_cart_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='owner',
        ),
    ]
