# Generated by Django 3.2.1 on 2024-06-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0018_rename_user_cart_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='books_price',
            field=models.IntegerField(default=0),
        ),
    ]
