# Generated by Django 3.2.1 on 2024-06-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0020_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
