# Generated by Django 3.2.1 on 2024-06-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0022_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
    ]
