# Generated by Django 3.2.1 on 2024-06-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0023_alter_inventory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='book_held',
            field=models.IntegerField(default=0),
        ),
    ]
