# Generated by Django 3.2.1 on 2024-07-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0025_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
